name: datengeschichten
channels:
  - conda-forge
dependencies:
  - r-base
  - r-here
  - r-tm
  - r-snowballc
  - r-wordcloud
  - r-wordcloud2
  - r-rcolorbrewer
  - r-stringi
  - r-rcpp
  - r-webshot
  - r-htmlwidgets
  - r-rvest
  - r-ggplot2
  - r-dplyr
  - jupyter_contrib_nbextensions
