name: ir-datengeschichten
channels:
  - conda-forge
dependencies:
  - r-base
  - r-tidyverse
  - r-here
  - r-tm
  - r-snowballc
  - r-wordcloud
  - r-wordcloud2
  - r-rcolorbrewer
  - r-stringi
  - r-rcpp
  - r-webshot
  - r-htmlwidgets
  - r-rvest
  - r-ggplot2
  - r-dplyr
  - r-psych
  - r-quantpsyc
  - r-car
  - r-vioplot
  - jupyter_contrib_nbextensions
